### ISSUE TITLE
Do you have octabeacon usage detail?

### ISSUE THREAD

**Issue by jatu-studiobox** [taichunmin/line-simplebeacon-esp32#1]
Hi,

Do you have octobeacon usage detail? I am not sure, how to create each beacon setting?

Thank you very much :)

**Comment by taichunmin** [comment]
@jatu-studiobox https://taichunmin.idv.tw/blog/2021-03-06-line-octobeacon.html

**Comment by jatu-studiobox** [comment]
Thank you very much :)
